development:
  adapter: postgresql
  encoding: unicode
  database: appwrangler_development
  pool: 5
  username: ryanbales
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: appwrangler_test
  pool: 5
  username: ryanbales
  password:
