development:
  adapter: postgresql
  database: backups_manager_development
  pool: 9
test:
  adapter: postgresql
  database: backups_manager_test
  pool: 9
production:
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] %>
  
